fly-enable-material: LIME_SHULKER_BOX
fly-disable-material: RED_SHULKER_BOX
fly-enable-displayname: "&aВключено"
fly-disable-displayname: "&cВыключено"
checkfly-in-gui: true
commands:
  fly: true
  checkfly: true
  checkhealth: true
  checkfood: true
  sethealth: true
  setfood: true
  feed: true
  heal: true
  flyspeed: true
  checkflyspeed: true
  speed: true
  tp: true
  tphere: true
  checkspeed: true
  seeinv: true
  gmcheck: true
  nick: true
  realname: true
  clear: true
nick:
  menu-title: "Настройка ника"
  info-of-nick-display-name: "&aИнформация о нике"
  new-nick-display-name: "&a+ Новый ник"
  clear-nick-display-name: "&cСбросить ник"
messages:
  no-permissions: "&cНе достаточно прав!"
  player-not-found: "&cИгрок не найден!"
  fly-enable: "&aРежим полета включен!"
  fly-disable: "&cРежим полета выключен!"
  sender-not-player: "&cЭту команду могут выполнять только игроки!"
  health-level-big: "&cМаксимальный уровень здоровья: {max_health}"
  checkfly-menu-title: "Проверка режима полета"
  target-health-level: "&a{health_level}"
  target-food-level: "&a{food_level}"
  command-disable: "&cКоманда отключена"
  heal-command: "&aВы вылечили себя"
  heal-command-target: "&aВы вылечили игрока {player_name}"
  feed-command: "&aВы покормили себя"
  feed-command-target: "&aВы покормили игрока {player_name}"
  feed-command-target-me: "&aВас покормили"
  heal-command-target-me: "&aВас вылечили"
  tp-to-player: "&aВы были телепортированы к игроку {player_name}"
  tphere-target: "&aВы были телепортированы к игроку {player_name}"
  tp-target-is-player: "&cВы не можете телепортироваться к себе!"
  tphere-target-is-player: "&cВы не можете телепортировать себя к себе!"
  unknown-argument: "&cНеизвестный аргумент!"
  fly-enable-message: "&aДа"
  fly-disable-message: "&cНет"
  you-see-inv: "&aВы просматриваете инвентарь игрока {player_name}"
  seeinv-target-is-player: "&cВы итак можете посмотреть свой инвентарь!"
  change-nick: "&aВы изменили свой ник! Текущий ник: {currency_nick}"
  clear-nick: "&cВы сбросили свой ник"
  realname: "&aТекущий ник игрока {player_nick}: {player_name}"
  clear-inv: "&aВы отчистили себе инвентарь"
  clear-inv-other: "&aВы отчистили инвентарь игроку {player_name}"
  target-clear-inv: "&aВам отчистили инвентарь"
  target-change-nick: "&aВам поменяли ник"
  me-target-change-nick: "&aВы поменяли ник игроку {player_name}"
  ext-me: "&aВы потушили себя"
  ext-target-me: "&aВы потушили игрока {player_name}"
  ext-target: "&aВас потушили"